spring.application.name=bank-api

# Configuração Dinâmica (Usa variáveis do Railway ou H2 se local)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./bankdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

# JPA / Hibernate
spring.jpa.database-platform=${SPRING_JPA_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Console H2 (Só funciona se estiver rodando localmente)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=${PORT:8080}