services:
  postgres:
    image: postgres:16
    container_name: bank-api-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
    ports:
      - "5432:5432"
    volumes:
      - bank-api-pgdata:/var/lib/postgresql/data
volumes:
  bank-api-pgdata:
